// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using register.infra.data.Context;

namespace register.infra.data.Migrations
{
    [DbContext(typeof(RegisterDbContext))]
    [Migration("20201104200843_CustomerTable")]
    partial class CustomerTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("register.domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ed5e347-bd10-411f-89fc-fe7a13149087"),
                            Birthdate = new DateTime(2000, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            Gender = 1,
                            LastName = "Stout"
                        },
                        new
                        {
                            Id = new Guid("1ed5e347-bd10-411f-89fc-fe7a13149088"),
                            Birthdate = new DateTime(2005, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mary",
                            Gender = 2,
                            LastName = "Dunkel"
                        },
                        new
                        {
                            Id = new Guid("1ed5e347-bd10-411f-89fc-fe7a13149089"),
                            Birthdate = new DateTime(2000, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            Gender = 1,
                            LastName = "Pilsen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
