name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        
    - name: list
      run: ls
    - name: Restore dependencies
      run: dotnet restore root/src/register.api
    - name: Build
      run: dotnet build --no-restore root/src/register.api
    - name: Test
      run: dotnet test --no-build --verbosity normal root/src/register.api
